branches:
  only:
    - master

sudo: required

git:
    depth: 1

language: bash

services:
  - docker

before_install:
- docker build -t kcyeu/boost .

script:
- "curl -H 'Content-Type: application/json' --data '{\"source_type\": \"Branch\", \"source_name\": \"master\"}' -X POST https://registry.hub.docker.com/u/kcyeu/boost/trigger/51ef1c03-9c5c-4101-ab25-3fa4ecaf4c9e/"

